name: Build and push to Dockerhub

on:
  push:
    branches: [ "main" ]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Pull PostgresQL image from Dockerhub
        run: docker run -d -p 5432:5432 --name dailydo-postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=dailydo postgres
      - name: Build jar
        run: ./mvnw clean install
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: docker build -t andrehsvictor/dailydo-api:0.1 .
