name: Build and push to Dockerhub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Run PostgresQL image
        run: docker run -d -p 5432:5432 --name dailydo-postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=dailydo postgres
      - name: Build .jar file
        run: docker run -d maven mvn clean install
      - name: Build image
        run: docker buildx build -f Dockerfile -t andrehsvictor/dailydo-api:0.1 .
      - name: Dockerhub login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Dockerhub
        run: docker push andrehsvictor/dailydo-api:0.1
